# Generated by Django 4.2 on 2025-06-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighttracker', '0002_weightentry_delete_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
