# Generated by Django 4.2 on 2025-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighttracker', '0003_alter_weightentry_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
