# Generated by Django 4.2 on 2025-06-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weighttracker', '0007_alter_weightentry_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightentry',
            old_name='date_added',
            new_name='date_range',
        ),
    ]
