# Generated by Django 4.2 on 2025-06-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weighttracker', '0008_rename_date_added_weightentry_date_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightentry',
            old_name='date_range',
            new_name='date_added',
        ),
    ]
